### ISSUE TITLE
Warning after updating to Material UI v4

### ISSUE THREAD

**Issue by joharei** [szmslab/material-ui-flat-pagination#12]
We are getting this deprecation warning originating from `material-ui-flat-pagination` after updating Material UI to v4:
```
Warning: Material-UI: theme.spacing.unit usage has been deprecated.
It will be removed in v5.
You can replace `theme.spacing.unit * y` with `theme.spacing(y)`.

You can use the `https://github.com/mui-org/material-ui/tree/master/packages/material-ui-codemod/README.md#theme-spacing-api` migration helper to make the process smoother.
```

**Comment by oliviertassinari** [comment]
@szmslab I was looking at the components we miss in Material-UI core. I have found your pagination component in my recherche. Thank you for making it public! Do you have any plan with it going forward? It seems to be an important component, we have a nonnegligible search volume on the main documentation for the query `pagination`. I can think of two possible paths going forward:
1. We link it from https://material-ui.com/discover-more/related-projects/#libraries. This would make the component easier discoverable, it would also give it some credibility.
2. We use the component as inspiration for @material-ui/core. As far as I have talked with developers, they really value the fact of having a component directly supported in the core. It's one less package to update, that might create a conflict, it's issues like this one that is less likely to happen (as we apply changes globally on the mono-repository).

Do you guys have any preference?

**Comment by szmslab** [comment]
@joharei Released in v4.0.0. Supports Material-UI v4.

**Comment by szmslab** [comment]
@oliviertassinari Thank you for the suggestion. I prefer 1.

**Comment by oliviertassinari** [comment]
@szmslab Awesome, 1. sounds good to me, at least for the time being. We have some more important topic to handle, for instance: autocomplete, combobox, carousel, image, date range, dropzone, dropdow, alert, scrollspy. Do you want to submit a pull request to link your project in https://material-ui.com/discover-more/related-projects/#components? It could help with adoption :).

**Comment by szmslab** [comment]
@oliviertassinari Submitted a pull request. https://github.com/mui-org/material-ui/pull/17372
