### ISSUE TITLE
Use React 17 peer dependency (or remove peer dependency altogether)

### ISSUE THREAD

**Issue by aarowman** [szmslab/material-ui-flat-pagination#35]
Right now we have a peer dependency of react 16.8.0, so a normal install fails if using react 17 without the peer dependency (or using `npm install material-ui-flat-pagination --force`). Instead of installing an old version of react as a peerDependency or requiring `--force`, it would be nice to use this plugin and be compatible with react 17.

Latest as of writing this: `react@17.0.2`

**Comment by szmslab** [comment]
Fixed in v4.1.2.
