### ISSUE TITLE
Pagination links

### ISSUE THREAD

**Issue by yanislav-igonin** [szmslab/material-ui-flat-pagination#9]
Hello.

Is it possible to add a prop, that describes element, that should be rendered for page number, e.g. Link from react-router? For example, I want to be able middle click on page number and it opens new browser tab.

Best regards,
Yanislav.

**Comment by yanislav-igonin** [comment]
Also, is there a way to add page start number? Now it always starts from 1, but some situations needed to start it from 0 or negative number.

**Comment by ValentinH** [comment]
@szmslab would you accept a PR adding support for using real links for each page button?

We could use a render prop API like:
```jsx
<Pagination
      offset={page - 1}
      limit={1}
      total={totalPages}
      renderItem={({offset, children}) => <a href={`/results?page=${offset}`}>{children}</a>}
 />
```

Default value for the prop could be `({children}) => children`

**Comment by szilarddoro** [comment]
Any updates on this one? @ValentinH 's PR would really be appreciated.
